#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

extract_endpoint_field() {
  local endpoint="$1"
  local field="$2"
  python - "$endpoint" "$field" <<'PY'
import sys
from urllib.parse import urlparse

endpoint = str(sys.argv[1] or "").strip()
field = str(sys.argv[2] or "").strip()
if "://" not in endpoint:
    endpoint = f"http://{endpoint}"
parsed = urlparse(endpoint)
if field == "host":
    print(parsed.hostname or "", end="")
elif field == "port":
    print("" if parsed.port is None else parsed.port, end="")
else:
    raise SystemExit(2)
PY
}

if [[ ! -f "$ROOT_DIR/.venv/bin/activate" ]]; then
  echo "error: missing virtual environment activate script: $ROOT_DIR/.venv/bin/activate" >&2
  exit 1
fi
source "$ROOT_DIR/.venv/bin/activate"

export PYTHONPATH="$ROOT_DIR:$ROOT_DIR/../verl:${PYTHONPATH:-}"

if [[ -z "${VERL_CONFIG_PATH:-}" ]]; then
  SIBLING_VERL_CONFIG="$ROOT_DIR/../verl/verl/trainer/config"
  if [[ -d "$SIBLING_VERL_CONFIG" ]]; then
    VERL_CONFIG_PATH="$SIBLING_VERL_CONFIG"
  else
    VERL_CONFIG_PATH="$(
      python -c "from pathlib import Path; import verl; print((Path(verl.__file__).resolve().parent / 'trainer' / 'config').as_posix())"
    )"
  fi
fi
if [[ -z "${VERL_CONFIG_PATH:-}" || ! -d "$VERL_CONFIG_PATH" ]]; then
  echo "error: unable to resolve VERL_CONFIG_PATH (set it explicitly or install local ../verl)" >&2
  exit 1
fi
export VERL_CONFIG_PATH

CONFIG_PATH="${CONFIG_PATH:-marco/verl/config/grpo_marco_fsdp_sglang.yaml}"
if [[ "$CONFIG_PATH" != /* ]]; then
  CONFIG_PATH="$ROOT_DIR/$CONFIG_PATH"
fi
CONFIG_DIR="$(dirname "$CONFIG_PATH")"
CONFIG_BASENAME="$(basename "$CONFIG_PATH")"
CONFIG_NAME="${CONFIG_BASENAME%.yaml}"
CONFIG_NAME="${CONFIG_NAME%.yml}"
MODEL_PATH="${MODEL_PATH:-Qwen/Qwen2.5-3B-Instruct}"
MODEL_PATH="${MODEL_PATH%/}"
TRAIN_PARQUET="${TRAIN_PARQUET:-data/rlhf_recomputed/train.parquet}"
VAL_PARQUET="${VAL_PARQUET:-data/rlhf_recomputed/val.parquet}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/verl_marco_rl_ord/qwen}"
PROJECT_NAME="${PROJECT_NAME:-marco-verl}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-ordinary-marco-rl}"

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-4096}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-1024}"
TOTAL_EPOCHS="${TOTAL_EPOCHS:-30}"
TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-null}"
ROLLOUT_MAX_RESPONSE_LEN="$MAX_RESPONSE_LENGTH"
export ROLLOUT_MAX_RESPONSE_LEN
MAX_TURNS="${MAX_TURNS:-${MARCO_MAX_TURNS:-5}}"

ROLLOUT_N="${ROLLOUT_N:-4}"
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
ROLLOUT_TOP_P="${ROLLOUT_TOP_P:-0.8}"
AGENT_NUM_WORKERS="${AGENT_NUM_WORKERS:-1}"
ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU="${ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
ACTOR_PPO_MINI_BATCH_SIZE="${ACTOR_PPO_MINI_BATCH_SIZE:-$TRAIN_BATCH_SIZE}"
ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="${ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE:-1}"
LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"

AGENT_LOOP_CONFIG_PATH="${AGENT_LOOP_CONFIG_PATH:-$ROOT_DIR/marco/verl/config/agent_loop/marco_agent_loop.yaml}"
INTERACTION_CONFIG_PATH="${INTERACTION_CONFIG_PATH:-$ROOT_DIR/marco/verl/config/interaction_config/marco_interaction.yaml}"

ADMET_PORT="${ADMET_PORT:-10086}"
DRD2_PORT="${DRD2_PORT:-10087}"
PREDICTOR_HOST="${PREDICTOR_HOST:-127.0.0.1}"
MARCO_ADMET_API="${MARCO_ADMET_API:-http://${PREDICTOR_HOST}:${ADMET_PORT}/predict/}"
MARCO_DRD2_API="${MARCO_DRD2_API:-http://${PREDICTOR_HOST}:${DRD2_PORT}/predict/}"
MARCO_PREDICTOR_CACHE_PATH="${MARCO_PREDICTOR_CACHE_PATH:-$ROOT_DIR/outputs/predictor_cache.sqlite3}"
MARCO_PREDICTOR_TIMEOUT_S="${MARCO_PREDICTOR_TIMEOUT_S:-60}"
MARCO_PREDICTOR_MAX_RETRIES="${MARCO_PREDICTOR_MAX_RETRIES:-0}"
PREDICTOR_REQUIRE_SEMANTIC_PROBE="${PREDICTOR_REQUIRE_SEMANTIC_PROBE:-1}"
ADMET_API_HOST="$(extract_endpoint_field "$MARCO_ADMET_API" host)"
ADMET_API_PORT="$(extract_endpoint_field "$MARCO_ADMET_API" port)"
DRD2_API_HOST="$(extract_endpoint_field "$MARCO_DRD2_API" host)"
DRD2_API_PORT="$(extract_endpoint_field "$MARCO_DRD2_API" port)"
if [[ -n "$ADMET_API_PORT" ]]; then
  ADMET_PORT="$ADMET_API_PORT"
fi
if [[ -n "$DRD2_API_PORT" ]]; then
  DRD2_PORT="$DRD2_API_PORT"
fi
if [[ -n "$ADMET_API_HOST" ]]; then
  PREDICTOR_HOST="$ADMET_API_HOST"
elif [[ -n "$DRD2_API_HOST" ]]; then
  PREDICTOR_HOST="$DRD2_API_HOST"
fi
export MARCO_ADMET_API
export MARCO_DRD2_API
export MARCO_PREDICTOR_CACHE_PATH
export MARCO_PREDICTOR_TIMEOUT_S
export MARCO_PREDICTOR_MAX_RETRIES
export PREDICTOR_REQUIRE_SEMANTIC_PROBE
export ADMET_PORT
export DRD2_PORT
export PREDICTOR_HOST

START_PREDICTORS="${START_PREDICTORS:-1}"
if [[ "$START_PREDICTORS" == "1" ]]; then
  PREDICTOR_EXPORTS="$(bash "$ROOT_DIR/scripts/verl/start_predictors.sh")"
  eval "$PREDICTOR_EXPORTS"
fi

NNODES="${NNODES:-1}"
N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-8}"
LOGGER="${LOGGER:-[console]}"
PYTHON_BIN="${PYTHON_BIN:-python}"
TRAINER_RESUME_MODE="${TRAINER_RESUME_MODE:-}"
TRAINER_RESUME_FROM_PATH="${TRAINER_RESUME_FROM_PATH:-}"
TRAINER_TEST_FREQ="${TRAINER_TEST_FREQ:-20}"
TRAINER_VAL_BEFORE_TRAIN="${TRAINER_VAL_BEFORE_TRAIN:-false}"
TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-}"
TRAINER_VALIDATION_DATA_DIR="${TRAINER_VALIDATION_DATA_DIR:-}"
TRAINER_EVAL_ROLLOUT_DIR="${TRAINER_EVAL_ROLLOUT_DIR:-}"
TRAINER_EVAL_SUBTASK="${TRAINER_EVAL_SUBTASK:-}"
TRAINER_EVAL_PARTITION="${TRAINER_EVAL_PARTITION:-seen}"
TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD="${TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD:-0.5}"
TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW="${TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW:-0.6}"
TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH="${TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH:-0.95}"
TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD="${TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD:-}"
VAL_MAX_SAMPLES="${VAL_MAX_SAMPLES:--1}"
VALIDATION_SHUFFLE="${VALIDATION_SHUFFLE:-true}"
VALIDATION_MODE="${VALIDATION_MODE:-sampled}"
VALIDATION_DO_SAMPLE="${VALIDATION_DO_SAMPLE:-}"
VALIDATION_TEMPERATURE="${VALIDATION_TEMPERATURE:-$ROLLOUT_TEMPERATURE}"
VALIDATION_TOP_P="${VALIDATION_TOP_P:-$ROLLOUT_TOP_P}"
VALIDATION_N="${VALIDATION_N:-1}"
ACTOR_LR="${ACTOR_LR:-}"
ACTOR_LR_SCHEDULER_TYPE="${ACTOR_LR_SCHEDULER_TYPE:-}"
ACTOR_LR_WARMUP_STEPS_RATIO="${ACTOR_LR_WARMUP_STEPS_RATIO:-}"
ACTOR_CHECKPOINT_LOAD_CONTENTS="${ACTOR_CHECKPOINT_LOAD_CONTENTS:-}"
USE_KL_LOSS="${USE_KL_LOSS:-}"
KL_LOSS_COEF="${KL_LOSS_COEF:-}"
KL_LOSS_TYPE="${KL_LOSS_TYPE:-}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-}"
ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-false}"
ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-}"
ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-}"
MARCO_REWARD_INVALID_PENALTY="${MARCO_REWARD_INVALID_PENALTY:-1.0}"
MARCO_DIRECTIONAL_PROGRESS_CLIP="${MARCO_DIRECTIONAL_PROGRESS_CLIP:-1.0}"
MARCO_SIMILARITY_TARGET_LOW="${MARCO_SIMILARITY_TARGET_LOW:-0.6}"
MARCO_SIMILARITY_TARGET_HIGH="${MARCO_SIMILARITY_TARGET_HIGH:-0.95}"
MARCO_SIMILARITY_COPY_THRESHOLD="${MARCO_SIMILARITY_COPY_THRESHOLD:-0.99}"
MARCO_SIMILARITY_LOW_WEIGHT="${MARCO_SIMILARITY_LOW_WEIGHT:-1.0}"
MARCO_SIMILARITY_COPY_PENALTY_WEIGHT="${MARCO_SIMILARITY_COPY_PENALTY_WEIGHT:-2.0}"
MARCO_PROGRESS_MIN_SIMILARITY="${MARCO_PROGRESS_MIN_SIMILARITY:-0.3}"
MARCO_LENGTH_PENALTY_THRESHOLD="${MARCO_LENGTH_PENALTY_THRESHOLD:-256}"
MARCO_LENGTH_PENALTY_VALUE="${MARCO_LENGTH_PENALTY_VALUE:-0.2}"
MARCO_STATE_PROP_WEIGHT="${MARCO_STATE_PROP_WEIGHT:-1.0}"
MARCO_STATE_SIM_WEIGHT="${MARCO_STATE_SIM_WEIGHT:-1.0}"
MARCO_QUALITY_SUCCESS_BONUS="${MARCO_QUALITY_SUCCESS_BONUS:-0.15}"
MARCO_TREND_IMPROVE_WEIGHT="${MARCO_TREND_IMPROVE_WEIGHT:-0.5}"
MARCO_TREND_REGRESS_WEIGHT="${MARCO_TREND_REGRESS_WEIGHT:-0.75}"
MARCO_TREND_IMPROVE_MARGIN="${MARCO_TREND_IMPROVE_MARGIN:-0.02}"
MARCO_TREND_REGRESS_MARGIN="${MARCO_TREND_REGRESS_MARGIN:-0.02}"
export MARCO_REWARD_INVALID_PENALTY
export MARCO_DIRECTIONAL_PROGRESS_CLIP
export MARCO_SIMILARITY_TARGET_LOW
export MARCO_SIMILARITY_TARGET_HIGH
export MARCO_SIMILARITY_COPY_THRESHOLD
export MARCO_SIMILARITY_LOW_WEIGHT
export MARCO_SIMILARITY_COPY_PENALTY_WEIGHT
export MARCO_PROGRESS_MIN_SIMILARITY
export MARCO_LENGTH_PENALTY_THRESHOLD
export MARCO_LENGTH_PENALTY_VALUE
export MARCO_STATE_PROP_WEIGHT
export MARCO_STATE_SIM_WEIGHT
export MARCO_QUALITY_SUCCESS_BONUS
export MARCO_TREND_IMPROVE_WEIGHT
export MARCO_TREND_REGRESS_WEIGHT
export MARCO_TREND_IMPROVE_MARGIN
export MARCO_TREND_REGRESS_MARGIN
VALIDATION_EVAL_WATCHER_PID=""

if [[ -z "$VALIDATION_DO_SAMPLE" ]]; then
  if [[ "$VALIDATION_MODE" == "sampled" ]]; then
    VALIDATION_DO_SAMPLE="true"
  else
    VALIDATION_DO_SAMPLE="false"
  fi
fi
if [[ "$VALIDATION_DO_SAMPLE" != "true" ]]; then
  VALIDATION_TEMPERATURE="0.0"
  VALIDATION_TOP_P="1.0"
fi

cleanup() {
  if [[ -n "${VALIDATION_EVAL_WATCHER_PID:-}" ]]; then
    kill "$VALIDATION_EVAL_WATCHER_PID" >/dev/null 2>&1 || true
    wait "$VALIDATION_EVAL_WATCHER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

EXTRA_ARGS=(
  "trainer.test_freq=$TRAINER_TEST_FREQ"
  "trainer.val_before_train=$TRAINER_VAL_BEFORE_TRAIN"
)
if [[ -n "$TRAINER_RESUME_MODE" ]]; then
  EXTRA_ARGS+=("trainer.resume_mode=$TRAINER_RESUME_MODE")
fi
if [[ -n "$TRAINER_RESUME_FROM_PATH" ]]; then
  EXTRA_ARGS+=("trainer.resume_from_path=$TRAINER_RESUME_FROM_PATH")
fi
if [[ -n "$TRAINER_SAVE_FREQ" ]]; then
  EXTRA_ARGS+=("trainer.save_freq=$TRAINER_SAVE_FREQ")
fi
if [[ -n "$TRAINER_VALIDATION_DATA_DIR" ]]; then
  EXTRA_ARGS+=("trainer.validation_data_dir=$TRAINER_VALIDATION_DATA_DIR")
fi
if [[ -n "$ACTOR_LR" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr=$ACTOR_LR")
fi
if [[ -n "$ACTOR_LR_SCHEDULER_TYPE" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr_scheduler_type=$ACTOR_LR_SCHEDULER_TYPE")
fi
if [[ -n "$ACTOR_LR_WARMUP_STEPS_RATIO" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=$ACTOR_LR_WARMUP_STEPS_RATIO")
fi
if [[ -n "$ACTOR_CHECKPOINT_LOAD_CONTENTS" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.checkpoint.load_contents=$ACTOR_CHECKPOINT_LOAD_CONTENTS")
fi
if [[ -n "$USE_KL_LOSS" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.use_kl_loss=$USE_KL_LOSS")
fi
if [[ -n "$KL_LOSS_COEF" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.kl_loss_coef=$KL_LOSS_COEF")
fi
if [[ -n "$KL_LOSS_TYPE" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.kl_loss_type=$KL_LOSS_TYPE")
fi
if [[ -n "$ROLLOUT_GPU_MEMORY_UTILIZATION" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.rollout.gpu_memory_utilization=$ROLLOUT_GPU_MEMORY_UTILIZATION")
fi
if [[ -n "$ROLLOUT_ENFORCE_EAGER" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.rollout.enforce_eager=$ROLLOUT_ENFORCE_EAGER")
fi
if [[ -n "$ROLLOUT_MAX_NUM_SEQS" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.rollout.max_num_seqs=$ROLLOUT_MAX_NUM_SEQS")
fi
if [[ -n "$ROLLOUT_MAX_NUM_BATCHED_TOKENS" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.rollout.max_num_batched_tokens=$ROLLOUT_MAX_NUM_BATCHED_TOKENS")
fi
EXTRA_ARGS+=("$@")

if [[ -n "$TRAINER_VALIDATION_DATA_DIR" && -n "$TRAINER_EVAL_ROLLOUT_DIR" ]]; then
  mkdir -p "$TRAINER_EVAL_ROLLOUT_DIR"
  TRAINER_VALIDATION_DATA_DIR="$TRAINER_VALIDATION_DATA_DIR" \
    TRAINER_EVAL_ROLLOUT_DIR="$TRAINER_EVAL_ROLLOUT_DIR" \
    CONFIG_PATH="$CONFIG_PATH" \
    CONFIG_NAME="$CONFIG_NAME" \
    PROJECT_NAME="$PROJECT_NAME" \
    EXPERIMENT_NAME="$EXPERIMENT_NAME" \
    MODEL_PATH="$MODEL_PATH" \
    TRAIN_PARQUET="$TRAIN_PARQUET" \
    VAL_PARQUET="$VAL_PARQUET" \
    OUTPUT_DIR="$OUTPUT_DIR" \
    TRAIN_BATCH_SIZE="$TRAIN_BATCH_SIZE" \
    MAX_PROMPT_LENGTH="$MAX_PROMPT_LENGTH" \
    MAX_RESPONSE_LENGTH="$MAX_RESPONSE_LENGTH" \
    TOTAL_EPOCHS="$TOTAL_EPOCHS" \
    TOTAL_TRAINING_STEPS="$TOTAL_TRAINING_STEPS" \
    MAX_TURNS="$MAX_TURNS" \
    ROLLOUT_N="$ROLLOUT_N" \
    ROLLOUT_TEMPERATURE="$ROLLOUT_TEMPERATURE" \
    ROLLOUT_TOP_P="$ROLLOUT_TOP_P" \
    ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="$ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE" \
    ROLLOUT_GPU_MEMORY_UTILIZATION="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    ROLLOUT_ENFORCE_EAGER="$ROLLOUT_ENFORCE_EAGER" \
    ROLLOUT_MAX_NUM_SEQS="$ROLLOUT_MAX_NUM_SEQS" \
    ROLLOUT_MAX_NUM_BATCHED_TOKENS="$ROLLOUT_MAX_NUM_BATCHED_TOKENS" \
    AGENT_NUM_WORKERS="$AGENT_NUM_WORKERS" \
    ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU="$ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU" \
    ACTOR_PPO_MINI_BATCH_SIZE="$ACTOR_PPO_MINI_BATCH_SIZE" \
    LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
    ACTOR_LR="$ACTOR_LR" \
    ACTOR_LR_SCHEDULER_TYPE="$ACTOR_LR_SCHEDULER_TYPE" \
    ACTOR_LR_WARMUP_STEPS_RATIO="$ACTOR_LR_WARMUP_STEPS_RATIO" \
    ACTOR_CHECKPOINT_LOAD_CONTENTS="$ACTOR_CHECKPOINT_LOAD_CONTENTS" \
    NNODES="$NNODES" \
    N_GPUS_PER_NODE="$N_GPUS_PER_NODE" \
    CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-}" \
    TRAINER_EVAL_SUBTASK="$TRAINER_EVAL_SUBTASK" \
    TRAINER_EVAL_PARTITION="$TRAINER_EVAL_PARTITION" \
    TRAINER_EVAL_MODE="$VALIDATION_MODE" \
    TRAINER_TEST_FREQ="$TRAINER_TEST_FREQ" \
    TRAINER_SAVE_FREQ="$TRAINER_SAVE_FREQ" \
    TRAINER_RESUME_MODE="$TRAINER_RESUME_MODE" \
    TRAINER_RESUME_FROM_PATH="$TRAINER_RESUME_FROM_PATH" \
    TRAINER_VAL_BEFORE_TRAIN="$TRAINER_VAL_BEFORE_TRAIN" \
    VALIDATION_MODE="$VALIDATION_MODE" \
    VALIDATION_DO_SAMPLE="$VALIDATION_DO_SAMPLE" \
    VALIDATION_TEMPERATURE="$VALIDATION_TEMPERATURE" \
    VALIDATION_TOP_P="$VALIDATION_TOP_P" \
    VALIDATION_N="$VALIDATION_N" \
    VAL_MAX_SAMPLES="$VAL_MAX_SAMPLES" \
    VALIDATION_SHUFFLE="$VALIDATION_SHUFFLE" \
    TRAINER_RAW_EVAL_ROOT_DIR="$ROOT_DIR" \
    TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD="$TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD" \
    TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW="$TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW" \
    TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH="$TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH" \
    TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD="$TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD" \
    MARCO_REWARD_INVALID_PENALTY="$MARCO_REWARD_INVALID_PENALTY" \
    MARCO_DIRECTIONAL_PROGRESS_CLIP="$MARCO_DIRECTIONAL_PROGRESS_CLIP" \
    MARCO_SIMILARITY_TARGET_LOW="$MARCO_SIMILARITY_TARGET_LOW" \
    MARCO_SIMILARITY_TARGET_HIGH="$MARCO_SIMILARITY_TARGET_HIGH" \
    MARCO_SIMILARITY_COPY_THRESHOLD="$MARCO_SIMILARITY_COPY_THRESHOLD" \
    MARCO_SIMILARITY_LOW_WEIGHT="$MARCO_SIMILARITY_LOW_WEIGHT" \
    MARCO_SIMILARITY_COPY_PENALTY_WEIGHT="$MARCO_SIMILARITY_COPY_PENALTY_WEIGHT" \
    MARCO_PROGRESS_MIN_SIMILARITY="$MARCO_PROGRESS_MIN_SIMILARITY" \
    MARCO_LENGTH_PENALTY_THRESHOLD="$MARCO_LENGTH_PENALTY_THRESHOLD" \
    MARCO_LENGTH_PENALTY_VALUE="$MARCO_LENGTH_PENALTY_VALUE" \
    MARCO_STATE_PROP_WEIGHT="$MARCO_STATE_PROP_WEIGHT" \
    MARCO_STATE_SIM_WEIGHT="$MARCO_STATE_SIM_WEIGHT" \
    MARCO_QUALITY_SUCCESS_BONUS="$MARCO_QUALITY_SUCCESS_BONUS" \
    MARCO_TREND_IMPROVE_WEIGHT="$MARCO_TREND_IMPROVE_WEIGHT" \
    MARCO_TREND_REGRESS_WEIGHT="$MARCO_TREND_REGRESS_WEIGHT" \
    MARCO_TREND_IMPROVE_MARGIN="$MARCO_TREND_IMPROVE_MARGIN" \
    MARCO_TREND_REGRESS_MARGIN="$MARCO_TREND_REGRESS_MARGIN" \
    PYTHON_BIN="$PYTHON_BIN" \
    bash "$ROOT_DIR/scripts/verl/watch_validation_to_eval.sh" &
  VALIDATION_EVAL_WATCHER_PID=$!
fi

"$PYTHON_BIN" -m verl.trainer.main_ppo \
  --config-path "$CONFIG_DIR" \
  --config-name "$CONFIG_NAME" \
  data.train_files="$TRAIN_PARQUET" \
  data.val_files="$VAL_PARQUET" \
  data.val_max_samples="$VAL_MAX_SAMPLES" \
  data.validation_shuffle="$VALIDATION_SHUFFLE" \
  data.max_prompt_length="$MAX_PROMPT_LENGTH" \
  data.max_response_length="$MAX_RESPONSE_LENGTH" \
  data.train_batch_size="$TRAIN_BATCH_SIZE" \
  actor_rollout_ref.model.path="$MODEL_PATH" \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu="$ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU" \
  actor_rollout_ref.actor.ppo_mini_batch_size="$ACTOR_PPO_MINI_BATCH_SIZE" \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
  actor_rollout_ref.rollout.n="$ROLLOUT_N" \
  actor_rollout_ref.rollout.temperature="$ROLLOUT_TEMPERATURE" \
  actor_rollout_ref.rollout.top_p="$ROLLOUT_TOP_P" \
  actor_rollout_ref.rollout.val_kwargs.n="$VALIDATION_N" \
  actor_rollout_ref.rollout.val_kwargs.do_sample="$VALIDATION_DO_SAMPLE" \
  actor_rollout_ref.rollout.val_kwargs.temperature="$VALIDATION_TEMPERATURE" \
  actor_rollout_ref.rollout.val_kwargs.top_p="$VALIDATION_TOP_P" \
  actor_rollout_ref.rollout.agent.num_workers="$AGENT_NUM_WORKERS" \
  actor_rollout_ref.rollout.tensor_model_parallel_size="$ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE" \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
  actor_rollout_ref.rollout.agent.agent_loop_config_path="$AGENT_LOOP_CONFIG_PATH" \
  actor_rollout_ref.rollout.multi_turn.interaction_config_path="$INTERACTION_CONFIG_PATH" \
  actor_rollout_ref.rollout.multi_turn.max_assistant_turns="$MAX_TURNS" \
  trainer.default_local_dir="$OUTPUT_DIR" \
  trainer.project_name="$PROJECT_NAME" \
  trainer.experiment_name="$EXPERIMENT_NAME" \
  trainer.total_epochs="$TOTAL_EPOCHS" \
  trainer.total_training_steps="$TOTAL_TRAINING_STEPS" \
  trainer.nnodes="$NNODES" \
  trainer.n_gpus_per_node="$N_GPUS_PER_NODE" \
  trainer.logger="$LOGGER" \
  "${EXTRA_ARGS[@]}"
