#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -f "$ROOT_DIR/.venv/bin/activate" ]]; then
  echo "error: missing virtual environment activate script: $ROOT_DIR/.venv/bin/activate" >&2
  exit 1
fi
source "$ROOT_DIR/.venv/bin/activate"

export PYTHONPATH="$ROOT_DIR:$ROOT_DIR/../verl:${PYTHONPATH:-}"

if [[ -z "${VERL_CONFIG_PATH:-}" ]]; then
  SIBLING_VERL_CONFIG="$ROOT_DIR/../verl/verl/trainer/config"
  if [[ -d "$SIBLING_VERL_CONFIG" ]]; then
    VERL_CONFIG_PATH="$SIBLING_VERL_CONFIG"
  else
    VERL_CONFIG_PATH="$(
      python -c "from pathlib import Path; import verl; print((Path(verl.__file__).resolve().parent / 'trainer' / 'config').as_posix())"
    )"
  fi
fi
if [[ -z "${VERL_CONFIG_PATH:-}" || ! -d "$VERL_CONFIG_PATH" ]]; then
  echo "error: unable to resolve VERL_CONFIG_PATH (set it explicitly or install local ../verl)" >&2
  exit 1
fi
export VERL_CONFIG_PATH

MARCO_PREDICTOR_CACHE_PATH="${MARCO_PREDICTOR_CACHE_PATH:-$ROOT_DIR/outputs/predictor_cache.sqlite3}"
MARCO_PREDICTOR_TIMEOUT_S="${MARCO_PREDICTOR_TIMEOUT_S:-60}"
MARCO_PREDICTOR_MAX_RETRIES="${MARCO_PREDICTOR_MAX_RETRIES:-0}"
PREDICTOR_REQUIRE_SEMANTIC_PROBE="${PREDICTOR_REQUIRE_SEMANTIC_PROBE:-1}"
export MARCO_PREDICTOR_CACHE_PATH
export MARCO_PREDICTOR_TIMEOUT_S
export MARCO_PREDICTOR_MAX_RETRIES
export PREDICTOR_REQUIRE_SEMANTIC_PROBE

START_PREDICTORS="${START_PREDICTORS:-1}"
if [[ "$START_PREDICTORS" == "1" ]]; then
  PREDICTOR_EXPORTS="$(bash "$ROOT_DIR/scripts/verl/start_predictors.sh")"
  eval "$PREDICTOR_EXPORTS"
fi

CONFIG_PATH="${CONFIG_PATH:-marco/verl/config/grpo_repo_single_turn.yaml}"
if [[ "$CONFIG_PATH" != /* ]]; then
  CONFIG_PATH="$ROOT_DIR/$CONFIG_PATH"
fi
CONFIG_DIR="$(dirname "$CONFIG_PATH")"
CONFIG_BASENAME="$(basename "$CONFIG_PATH")"
CONFIG_NAME="${CONFIG_BASENAME%.yaml}"
CONFIG_NAME="${CONFIG_NAME%.yml}"
MODEL_PATH="${MODEL_PATH:-Qwen/Qwen2.5-3B-Instruct}"
TRAIN_PARQUET="${TRAIN_PARQUET:-data/grpo_single_turn_recomputed/train.parquet}"
VAL_PARQUET="${VAL_PARQUET:-data/grpo_single_turn_recomputed/val.parquet}"
PROJECT_NAME="${PROJECT_NAME:-marco-verl}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo-repo-single-turn}"
EXPERIMENT_DIR_NAME="${EXPERIMENT_DIR_NAME:-$EXPERIMENT_NAME}"
OUTPUT_DIR="${OUTPUT_DIR:-outputs/experiments/$EXPERIMENT_DIR_NAME/checkpoints}"
LOG_DIR="${LOG_DIR:-logs/experiments/$EXPERIMENT_DIR_NAME}"

MODEL_PATH="${MODEL_PATH%/}"
TRAIN_PARQUET="${TRAIN_PARQUET%/}"
VAL_PARQUET="${VAL_PARQUET%/}"

mkdir -p "$OUTPUT_DIR" "$LOG_DIR"

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-4096}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-512}"
ROLLOUT_N="${ROLLOUT_N:-8}"
ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-0.9}"
ROLLOUT_TOP_P="${ROLLOUT_TOP_P:-0.8}"
ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU="${ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
ACTOR_PPO_MINI_BATCH_SIZE="${ACTOR_PPO_MINI_BATCH_SIZE:-$TRAIN_BATCH_SIZE}"
ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="${ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE:-1}"
LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"

USE_KL_LOSS="${USE_KL_LOSS:-true}"
KL_LOSS_COEF="${KL_LOSS_COEF:-0.04}"
KL_LOSS_TYPE="${KL_LOSS_TYPE:-low_var_kl}"

NNODES="${NNODES:-1}"
N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-8}"
LOGGER="${LOGGER:-[console]}"
PYTHON_BIN="${PYTHON_BIN:-python}"
TRAINER_RESUME_MODE="${TRAINER_RESUME_MODE:-}"
TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-}"
TRAINER_TEST_FREQ="${TRAINER_TEST_FREQ:-}"
TRAINER_VAL_BEFORE_TRAIN="${TRAINER_VAL_BEFORE_TRAIN:-}"
TRAINER_VALIDATION_DATA_DIR="${TRAINER_VALIDATION_DATA_DIR:-}"
TRAINER_EVAL_ROLLOUT_DIR="${TRAINER_EVAL_ROLLOUT_DIR:-}"
TRAINER_ROLLOUT_DATA_DIR="${TRAINER_ROLLOUT_DATA_DIR:-}"
TRAINER_EVAL_SUBTASK="${TRAINER_EVAL_SUBTASK:-}"
TRAINER_EVAL_PARTITION="${TRAINER_EVAL_PARTITION:-seen}"
TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD="${TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD:-0.5}"
TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW="${TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW:-}"
TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH="${TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH:-}"
TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD="${TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD:-}"
TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-}"
ACTOR_LR="${ACTOR_LR:-}"
ACTOR_LR_SCHEDULER_TYPE="${ACTOR_LR_SCHEDULER_TYPE:-}"
ACTOR_LR_WARMUP_STEPS_RATIO="${ACTOR_LR_WARMUP_STEPS_RATIO:-}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-}"
MARCO_REPO_SIM_THRESHOLD="${MARCO_REPO_SIM_THRESHOLD:-0.5}"
export MARCO_REPO_SIM_THRESHOLD
MARCO_REPO_EXACT_COPY_SCORE_ZERO="${MARCO_REPO_EXACT_COPY_SCORE_ZERO:-0}"
export MARCO_REPO_EXACT_COPY_SCORE_ZERO
VALIDATION_MODE="${VALIDATION_MODE:-sampled}"
VALIDATION_DO_SAMPLE="${VALIDATION_DO_SAMPLE:-}"
VALIDATION_TEMPERATURE="${VALIDATION_TEMPERATURE:-$ROLLOUT_TEMPERATURE}"
VALIDATION_TOP_P="${VALIDATION_TOP_P:-$ROLLOUT_TOP_P}"
VALIDATION_N="${VALIDATION_N:-1}"
VALIDATION_EVAL_WATCHER_PID=""

if [[ -z "$VALIDATION_DO_SAMPLE" ]]; then
  if [[ "$VALIDATION_MODE" == "sampled" ]]; then
    VALIDATION_DO_SAMPLE="true"
  else
    VALIDATION_DO_SAMPLE="false"
  fi
fi
if [[ "$VALIDATION_DO_SAMPLE" != "true" ]]; then
  VALIDATION_TEMPERATURE="0.0"
  VALIDATION_TOP_P="1.0"
fi

cleanup() {
  if [[ -n "${VALIDATION_EVAL_WATCHER_PID:-}" ]]; then
    kill "$VALIDATION_EVAL_WATCHER_PID" >/dev/null 2>&1 || true
    wait "$VALIDATION_EVAL_WATCHER_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

EXTRA_ARGS=("$@")
if [[ -n "$TRAINER_RESUME_MODE" ]]; then
  EXTRA_ARGS+=("trainer.resume_mode=$TRAINER_RESUME_MODE")
fi
if [[ -n "$TRAINER_TOTAL_EPOCHS" ]]; then
  EXTRA_ARGS+=("trainer.total_epochs=$TRAINER_TOTAL_EPOCHS")
fi
if [[ -n "$TRAINER_TEST_FREQ" ]]; then
  EXTRA_ARGS+=("trainer.test_freq=$TRAINER_TEST_FREQ")
fi
if [[ -n "$TRAINER_VAL_BEFORE_TRAIN" ]]; then
  EXTRA_ARGS+=("trainer.val_before_train=$TRAINER_VAL_BEFORE_TRAIN")
fi
if [[ -n "$TRAINER_VALIDATION_DATA_DIR" ]]; then
  EXTRA_ARGS+=("trainer.validation_data_dir=$TRAINER_VALIDATION_DATA_DIR")
fi
if [[ -n "$TRAINER_ROLLOUT_DATA_DIR" ]]; then
  mkdir -p "$TRAINER_ROLLOUT_DATA_DIR"
  EXTRA_ARGS+=("trainer.rollout_data_dir=$TRAINER_ROLLOUT_DATA_DIR")
fi
if [[ -n "$TRAINER_SAVE_FREQ" ]]; then
  EXTRA_ARGS+=("trainer.save_freq=$TRAINER_SAVE_FREQ")
fi
if [[ -n "$ACTOR_LR" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr=$ACTOR_LR")
fi
if [[ -n "$ACTOR_LR_SCHEDULER_TYPE" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr_scheduler_type=$ACTOR_LR_SCHEDULER_TYPE")
fi
if [[ -n "$ACTOR_LR_WARMUP_STEPS_RATIO" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=$ACTOR_LR_WARMUP_STEPS_RATIO")
fi
if [[ -n "$ROLLOUT_GPU_MEMORY_UTILIZATION" ]]; then
  EXTRA_ARGS+=("actor_rollout_ref.rollout.gpu_memory_utilization=$ROLLOUT_GPU_MEMORY_UTILIZATION")
fi

if [[ -n "$TRAINER_VALIDATION_DATA_DIR" && -n "$TRAINER_EVAL_ROLLOUT_DIR" ]]; then
  mkdir -p "$TRAINER_EVAL_ROLLOUT_DIR"
  TRAINER_VALIDATION_DATA_DIR="$TRAINER_VALIDATION_DATA_DIR" \
    TRAINER_EVAL_ROLLOUT_DIR="$TRAINER_EVAL_ROLLOUT_DIR" \
    CONFIG_PATH="$CONFIG_PATH" \
    CONFIG_NAME="$CONFIG_NAME" \
    PROJECT_NAME="$PROJECT_NAME" \
    EXPERIMENT_NAME="$EXPERIMENT_NAME" \
    MODEL_PATH="$MODEL_PATH" \
    TRAIN_PARQUET="$TRAIN_PARQUET" \
    VAL_PARQUET="$VAL_PARQUET" \
    OUTPUT_DIR="$OUTPUT_DIR" \
    LOG_DIR="$LOG_DIR" \
    TRAIN_BATCH_SIZE="$TRAIN_BATCH_SIZE" \
    MAX_PROMPT_LENGTH="$MAX_PROMPT_LENGTH" \
    MAX_RESPONSE_LENGTH="$MAX_RESPONSE_LENGTH" \
    TRAINER_TOTAL_EPOCHS="$TRAINER_TOTAL_EPOCHS" \
    TRAINER_TEST_FREQ="$TRAINER_TEST_FREQ" \
    TRAINER_SAVE_FREQ="$TRAINER_SAVE_FREQ" \
    TRAINER_RESUME_MODE="$TRAINER_RESUME_MODE" \
    TRAINER_VAL_BEFORE_TRAIN="$TRAINER_VAL_BEFORE_TRAIN" \
    ROLLOUT_N="$ROLLOUT_N" \
    ROLLOUT_TEMPERATURE="$ROLLOUT_TEMPERATURE" \
    ROLLOUT_TOP_P="$ROLLOUT_TOP_P" \
    ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="$ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE" \
    ROLLOUT_GPU_MEMORY_UTILIZATION="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU="$ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU" \
    ACTOR_PPO_MINI_BATCH_SIZE="$ACTOR_PPO_MINI_BATCH_SIZE" \
    LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
    ACTOR_LR="$ACTOR_LR" \
    ACTOR_LR_SCHEDULER_TYPE="$ACTOR_LR_SCHEDULER_TYPE" \
    ACTOR_LR_WARMUP_STEPS_RATIO="$ACTOR_LR_WARMUP_STEPS_RATIO" \
    USE_KL_LOSS="$USE_KL_LOSS" \
    KL_LOSS_COEF="$KL_LOSS_COEF" \
    KL_LOSS_TYPE="$KL_LOSS_TYPE" \
    NNODES="$NNODES" \
    N_GPUS_PER_NODE="$N_GPUS_PER_NODE" \
    CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-}" \
    TRAINER_EVAL_SUBTASK="$TRAINER_EVAL_SUBTASK" \
    TRAINER_EVAL_PARTITION="$TRAINER_EVAL_PARTITION" \
    TRAINER_EVAL_MODE="$VALIDATION_MODE" \
    VALIDATION_MODE="$VALIDATION_MODE" \
    VALIDATION_DO_SAMPLE="$VALIDATION_DO_SAMPLE" \
    VALIDATION_TEMPERATURE="$VALIDATION_TEMPERATURE" \
    VALIDATION_TOP_P="$VALIDATION_TOP_P" \
    VALIDATION_N="$VALIDATION_N" \
    TRAINER_RAW_EVAL_ROOT_DIR="$ROOT_DIR" \
    TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD="$TRAINER_RAW_EVAL_SIMILARITY_THRESHOLD" \
    TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW="$TRAINER_RAW_EVAL_SIMILARITY_TARGET_LOW" \
    TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH="$TRAINER_RAW_EVAL_SIMILARITY_TARGET_HIGH" \
    TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD="$TRAINER_RAW_EVAL_SIMILARITY_COPY_THRESHOLD" \
    MARCO_REPO_SIM_THRESHOLD="$MARCO_REPO_SIM_THRESHOLD" \
    MARCO_REPO_EXACT_COPY_SCORE_ZERO="$MARCO_REPO_EXACT_COPY_SCORE_ZERO" \
    PYTHON_BIN="$PYTHON_BIN" \
    bash "$ROOT_DIR/scripts/verl/watch_validation_to_eval.sh" &
  VALIDATION_EVAL_WATCHER_PID=$!
fi

"$PYTHON_BIN" -m verl.trainer.main_ppo \
  --config-path "$CONFIG_DIR" \
  --config-name "$CONFIG_NAME" \
  data.train_files="$TRAIN_PARQUET" \
  data.val_files="$VAL_PARQUET" \
  data.train_batch_size="$TRAIN_BATCH_SIZE" \
  data.max_prompt_length="$MAX_PROMPT_LENGTH" \
  data.max_response_length="$MAX_RESPONSE_LENGTH" \
  actor_rollout_ref.model.path="$MODEL_PATH" \
  actor_rollout_ref.actor.use_kl_loss="$USE_KL_LOSS" \
  actor_rollout_ref.actor.kl_loss_coef="$KL_LOSS_COEF" \
  actor_rollout_ref.actor.kl_loss_type="$KL_LOSS_TYPE" \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu="$ACTOR_PPO_MICRO_BATCH_SIZE_PER_GPU" \
  actor_rollout_ref.actor.ppo_mini_batch_size="$ACTOR_PPO_MINI_BATCH_SIZE" \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
  actor_rollout_ref.rollout.n="$ROLLOUT_N" \
  actor_rollout_ref.rollout.temperature="$ROLLOUT_TEMPERATURE" \
  actor_rollout_ref.rollout.top_p="$ROLLOUT_TOP_P" \
  actor_rollout_ref.rollout.val_kwargs.n="$VALIDATION_N" \
  actor_rollout_ref.rollout.val_kwargs.do_sample="$VALIDATION_DO_SAMPLE" \
  actor_rollout_ref.rollout.val_kwargs.temperature="$VALIDATION_TEMPERATURE" \
  actor_rollout_ref.rollout.val_kwargs.top_p="$VALIDATION_TOP_P" \
  actor_rollout_ref.rollout.tensor_model_parallel_size="$ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE" \
  actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu="$LOG_PROB_MICRO_BATCH_SIZE_PER_GPU" \
  trainer.default_local_dir="$OUTPUT_DIR" \
  trainer.project_name="$PROJECT_NAME" \
  trainer.experiment_name="$EXPERIMENT_NAME" \
  trainer.nnodes="$NNODES" \
  trainer.n_gpus_per_node="$N_GPUS_PER_NODE" \
  trainer.logger="$LOGGER" \
  "${EXTRA_ARGS[@]}"
